#version 450 core

#include "fluidCommon.glsl"

layout (local_size_x = 256) in;
//const uint NUM_PARTICLES = 10000u;

void main() {
    uint i = gl_GlobalInvocationID.x;
//    if (i >= NUM_PARTICLES) return;
    if(i >= uint(numParticles)) return;
    Particle p = particles[i];

//    p.pos.x += 1;

    p.pos.xyz = confine(p.pos.xyz);
    p.vel.xyz = (p.pos.xyz - p.oldPos.xyz) / dt;

    particles[i] = p;
}
